### ISSUE TITLE
Cannot find name 'HTMLVideoElementEventMap' in vue-test/node_modules/@daybrush/utils/declaration/types.d.ts(8,145)

### ISSUE THREAD

**Issue by leeboo** [daybrush/vue-test#1]
![image](https://user-images.githubusercontent.com/1256745/83965071-90e21680-a8e3-11ea-9973-6be665abc353.png)

**Comment by daybrush** [comment]
@leeboo 
pull and retest this.

Updated utils

**Comment by daybrush** [comment]
@leeboo 

https://github.com/daybrush/vue-test/blob/master/src/designMoveableHandler.ts#L7

Do not use react-moveable.

```js
import {OnDragEnd} from 'moveable'
```

**Comment by leeboo** [comment]
thank you :) 👍
